비밀번호 찾기 기능 구현
CHZZK-Study/Balance-Talk-Backend pull request #205
Opened 2024-03-16 09:23 UTC by jschoi-96

## 💡 작업 내용
- [x] 이메일로 임시 비밀번호 발급하는 기능 구현
- [x] 임시 비밀번호 발급 후, 데이터베이스에 저장된 회원 비밀번호 변경
- [x] 단위 테스트 추가

## 💡 자세한 설명

<img width="208" alt="스크린샷 2024-03-16 오후 6 14 45" src="https://github.com/CHZZK-Study/Balance-Talk-Backend/assets/78118588/1d443941-add6-4305-a1be-4e4ede5db322">

회원 가입 한 회원의 이메일로 임시 비밀번호가 발송되고 나면, 암호화가 되어 기존 비밀번호가 변경됩니다.

## 변경 전 
<img width="424" alt="스크린샷 2024-03-16 오후 6 14 05" src="https://github.com/CHZZK-Study/Balance-Talk-Backend/assets/78118588/d01c4cfd-f491-4fde-8eb7-47e8617995c0">

## 변경 후
<img width="420" alt="스크린샷 2024-03-16 오후 6 14 26" src="https://github.com/CHZZK-Study/Balance-Talk-Backend/assets/78118588/ee9b75a7-580c-4394-94c7-938e7c1aab9a">

### 변경 로직
<img width="622" alt="스크린샷 2024-03-16 오후 6 17 34" src="https://github.com/CHZZK-Study/Balance-Talk-Backend/assets/78118588/5c873292-4141-48fc-97ad-153662b326ad">

### 예외 처리
<img width="538" alt="스크린샷 2024-03-16 오후 6 22 21" src="https://github.com/CHZZK-Study/Balance-Talk-Backend/assets/78118588/69deb63d-01d3-4b4a-bfdc-4ad60bd441f7">

미 회원 가입된 이메일로 임시 비밀번호가 전송되지 않습니다.

## 📗 참고 자료 (선택)

## 📢 리뷰 요구 사항 (선택)

## 🚩 후속 작업 (선택)

## ✅ 셀프 체크리스트
- [x] PR 제목을 형식에 맞게 작성했나요?
- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있나요? (master/main이 아닙니다.)
- [x] 이슈는 close 했나요?
- [x] Reviewers, Labels, Projects를 등록했나요?
- [x] 작업 도중 문서 수정이 필요한 경우 잘 수정했나요?
- [x] 테스트는 잘 통과했나요?
- [x] 불필요한 코드는 제거했나요?

closes #200

2024-03-16 11:40 UTC, Hanjaemo requested changes
비밀번호 형식이 영문+숫자+특수문자 일텐데, 그러면 임시 비밀번호가 저장이 안되는거 아닌가요?>

2024-03-16 11:40 UTC, Hanjaemo commented on src/main/java/balancetalk/module/authmail/presentation/MailController.java
> +        mailService.sendTempCode(request);
tempCode보다는 authenticationNumber같은 네이밍은 어떨까요?

2024-03-16 11:40 UTC, Hanjaemo commented on src/main/java/balancetalk/module/authmail/application/MailService.java
> +        Member member = memberRepository.findByEmail(request.getEmail()).get();
get()으로 직접 꺼내오기 보다는 orElseThrow로 유효하지 않은 이메일인 경우 예외를 발생시키는 게 좋을 것 같아요

2024-03-16 11:40 UTC, Hanjaemo commented on src/main/java/balancetalk/module/authmail/application/MailService.java
> +        memberRepository.save(member);
변경 감지되니까 `memberRepository.save(member)`는 없어도 되지 않나요??

2024-03-16 11:40 UTC, Hanjaemo commented on src/main/java/balancetalk/module/authmail/application/MailService.java
> +        return UUID.randomUUID().toString().substring(0, 6);
상수 처리가 필요할 듯 합니다

2024-03-16 11:41 UTC, Hanjaemo commented on src/main/java/balancetalk/module/authmail/application/MailService.java
>      }
비밀번호 형식이 영문+숫자+특수문자 일텐데, 그러면 임시 비밀번호가 저장이 안되는거 아닌가요?

2024-03-16 13:26 UTC, jschoi-96 commented on src/main/java/balancetalk/module/authmail/presentation/MailController.java
> +        mailService.sendTempCode(request);
더 명확해지는 것 같네요!

2024-03-16 13:30 UTC, jschoi-96 commented on src/main/java/balancetalk/module/authmail/application/MailService.java
> +        Member member = memberRepository.findByEmail(request.getEmail()).get();
```java
    public void sendTempPassword(EmailRequest request) {
        if (!memberRepository.existsByEmail(request.getEmail())) {
            throw new BalanceTalkException(ErrorCode.NOT_FOUND_MEMBER);
        }
        MimeMessage message = createTempPassword(request);
        javaMailSender.send(message);
    }
```

제가 이메일을 보내는 메서드에서 회원 가입 여부를 체크하고 있었는데 `updateTempPassword` 메서드에서 미리 체크하면 더 깔끔할 것 같네요! 위 에러 체크는 없애구요.

2024-03-16 15:09 UTC, jschoi-96 commented on src/main/java/balancetalk/module/authmail/application/MailService.java
>      }
영문, 숫자, 특수문자 한개씩 포함되도록 수정했습니다!

2024-03-17 09:49 UTC, gywns0417 approved these changes

2024-03-19 10:48 UTC, Hanjaemo approved these changes

2024-03-19 10:49 UTC, merged