댓글 기능 수정 (프론트 요청 사항) 완료
CHZZK-Study/Balance-Talk-Backend pull request #625
Opened 2024-10-10 16:27 UTC by gywns0417

## 💡 작업 내용
- [ ] 댓글 조회 시 edited 값이 기본적으로 true인 버그 픽스
- [ ] 답글 응답 시 페이지네이션 대신 하나의 배열로 반환
- [ ] 댓글 DTO 에서 isBlind 필드 삭제, 최신순 조회에서 isBest 필드 삭제
- [ ] Best 댓글 조회 시 정렬 로직 수정

## 💡 자세한 설명
### postman 테스트 완료

### 댓글 조회 시 edited 값이 기본적으로 true인 버그 픽스
```java
public boolean isEdited() {
        return this.editedAt != null;
    }
```
`Comment` 엔티티 내에서 수정 여부를 판단할 때, 기존 로직은 편집일(`editedAt`) 필드가 null인지 여부로 판단합니다.

하지만 `CommentDto` 에서는 댓글 생성 시 `editedAt(LocalDateTime.now())` 를 사용해 최초 편집일을 생성일과 동일하게 만들어 주고 있습니다. 그 이유는 마이페이지에서 댓글 관련 조회 시, 생성일이 아닌 편집일 기준으로 정렬하기 때문입니다.

따라서 DTO에서 `editedAt` 필드를 수정할 수 없으므로, `Comment` 엔티티 내부에 
```java
    private boolean isEdited;

    public void setIsEdited() {
        this.isEdited = true;
    }
```
`isEdited` 필드를 하나 생성해주고, 기본값은 false로, 그리고 댓글 수정시에는 `setIsEdited()` 메서드를 사용해 해당 필드값을 true로 바꿔주게 구현했습니다. (ERD 반영 완료)

### Best 댓글 조회 시 정렬 로직 수정

```java
bestComments.sort(Comparator.comparing(CommentOrderByBestResponse::getCreatedAt).reversed());
otherComments.sort(Comparator.comparing(CommentOrderByBestResponse::getCreatedAt).reversed());
```

기존의 BEST 댓글 조회 로직에서는, 날짜가 내림차순이 아닌 오름차순 정렬임을 발견했습니다.
플로우상 내림차순 정렬이 되어야 하므로, `reserved()` 메서드를 사용했습니다.

## 📗 참고 자료 (선택)

## 📢 리뷰 요구 사항 (선택)

## 🚩 후속 작업 (선택)

## ✅ 셀프 체크리스트
- [ ] PR 제목을 형식에 맞게 작성했나요?
- [ ] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있나요?
- [ ] 이슈는 close 했나요?
- [ ] Reviewers, Labels, Projects를 등록했나요?
- [ ] 작업 도중 문서 수정이 필요한 경우 잘 수정했나요?
- [ ] 테스트는 잘 통과했나요?
- [ ] 불필요한 코드는 제거했나요?

closes #624

2024-10-11 19:21 UTC, Hanjaemo requested changes

2024-10-11 19:21 UTC, Hanjaemo commented on src/main/java/balancetalk/comment/dto/CommentDto.java
> +    public static class CommentOrderByCreatedAtResponse {
최신순으로 댓글을 조회하는 기능은 상황에 따라 구현 내용이 달라질 수 있을 것 같아요.
그런 의미에서 포괄적이면서 의미를 직관적으로 나타낼 수 있는 LatestCommentResponse라는 네이밍이 더 괜찮다고 생각합니다!
어떻게 생각하시나요??

2024-10-11 19:21 UTC, Hanjaemo commented on src/main/java/balancetalk/comment/dto/CommentDto.java
> +    public static class CommentOrderByBestResponse {
> 최신순으로 댓글을 조회하는 기능은 상황에 따라 구현 내용이 달라질 수 있을 것 같아요.
> 그런 의미에서 포괄적이면서 의미를 직관적으로 나타낼 수 있는 LatestCommentResponse라는 네이밍이 더 괜찮다고 생각합니다!
> 어떻게 생각하시나요??

동일한 내용입니다.

2024-10-11 19:21 UTC, Hanjaemo commented on src/main/java/balancetalk/comment/application/CommentService.java
> +        if (!member.hasVotedTalkPick(talkPick) && !talkPick.getMember().equals(member)) {
> !talkPick.getMember().equals(member)
> 댓글을 작성하려는 회원이 톡픽 작성자가 아닌 경우 왜 NOT_FOUND_VOTE 예외를 터뜨릴까요??

동일한 내용입니다.

2024-10-11 19:21 UTC, Hanjaemo commented on src/main/java/balancetalk/comment/domain/Comment.java
>      }
`setIsEdited` 메서드는 단순히 `isEdited` 값을 true로 변경하는 역할만 하므로, 불필요한 메서드가 하나 추가된 느낌이 들어요. 이를 인라인으로 처리하면 더 가독성 좋은 코드가 될 것 같은데 어떻게 생각하시나요?

2024-10-12 12:42 UTC, gywns0417 commented on src/main/java/balancetalk/comment/application/CommentService.java
> +        if (!member.hasVotedTalkPick(talkPick) && !talkPick.getMember().equals(member)) {
댓글 플로우상, 투표하지 않은 회원은 댓글을 작성할 수 없기 때문입니다!
다만, 투표를 하지 않더라도 톡픽 작성자인 경우에는 댓글을 작성할 수 있기에, `!talkPick.getMember().equals(member)` 조건을 추가했습니다.

2024-10-12 12:42 UTC, gywns0417 commented on src/main/java/balancetalk/comment/application/CommentService.java
> +        if (!member.hasVotedTalkPick(talkPick) && !talkPick.getMember().equals(member)) {
위에 답변 달았습니다!

2024-10-12 12:42 UTC, gywns0417 commented on src/main/java/balancetalk/comment/dto/CommentDto.java
> +    public static class CommentOrderByCreatedAtResponse {
오.. 안 그래도 네이밍 고민됐었는데, 감사합니다!

2024-10-12 12:42 UTC, gywns0417 commented on src/main/java/balancetalk/comment/dto/CommentDto.java
> +    public static class CommentOrderByBestResponse {
수정하겠습니다!

2024-10-12 12:42 UTC, gywns0417 commented on src/main/java/balancetalk/comment/domain/Comment.java
>      }
동의합니다! 감사합니다~

2024-10-13 16:42 UTC, Hanjaemo commented on src/main/java/balancetalk/comment/application/CommentService.java
> +        if (!member.hasVotedTalkPick(talkPick) && !talkPick.getMember().equals(member)) {
설명 덕분에 코드를 작성한 이유는 알겠습니다!
다만, 다음과 같이 댓글 작성 권한 로직을 캡슐화하면 어떨까 싶어요.
```java
if (member.cannotWriteComment(talkPick)) {
    throw new ...
}
```
```java
public class Member {
    public boolean cannotWriteComment(TalkPick talkPick) {
        return !this.hasVotedTalkPick(talkPick) && !this.isWriterOf(talkPick);
    }

    private boolean isWriterOf(TalkPick talkPick) {
        return talkPicks.contains(talkPick);
    }
}
```

이렇게 작성하면, `createComment` 메서드에서는 권한 체크가 간결해지고, 실제 권한 검사 로직은 Member 클래스 내부로 캡슐화되므로 코드가 더욱 명확해질 듯 합니다.
나중에 댓글 작성 권한 로직이 변경될 때도 Member 클래스만 변경하면 되니까요!

2024-10-14 05:37 UTC, gywns0417 commented on src/main/java/balancetalk/comment/application/CommentService.java
> +        if (!member.hasVotedTalkPick(talkPick) && !talkPick.getMember().equals(member)) {
캡슐화... 좋은 의견 감사합니다!! 수정할게요 !

2024-10-14 11:35 UTC, Hanjaemo approved these changes

2024-10-14 11:47 UTC, merged